### ISSUE TITLE
starter is out of date (v0.2.x vs v0.6.x)

### ISSUE THREAD

**Issue by bdougie** [superawesomelabs/leo-blog-starter#2]
I am trying to check out this `leo` project using the setup in the README. Is there somewhere I need to add a GraphQL/Relay URL somewhere to point.

Is there a step missing? 

```sh
/Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-plugin-markdown/index.js:11
      instance: opts.instance || require('markdown-it')({
                    ^
TypeError: Cannot read property 'instance' of undefined
    at config.merge (/Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-plugin-markdown/index.js:11:21)
    at Config.merge (/Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack-configurator/index.js:28:24)
    at configure (/Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-plugin-markdown/index.js:8:10)
    at /Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-core/build/leo.js:1044:21
    at Array.forEach (native)
    at enablePlugins (/Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-core/build/leo.js:1041:12)
    at exports.default (/Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-core/build/leo.js:1008:39)
    at /Users/bdougie/Desktop/leo-blog-starter/node_modules/@sa-labs/leo-core/build/leo.js:799:72
    at /Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack-require/lib/webpackRequire.js:121:7
    at /Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack-require/lib/webpackRequire.js:80:5
    at Compiler.<anonymous> (/Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/bdougie/Desktop/leo-blog-starter/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/bdougie/Desktop/leo-blog-starter/node_modules/webpack/lib/Compiler.js:272:8)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/bdougie/.nvm/versions/node/v6.8.0/bin/node" "/Users/bdougie/.nvm/versions/node/v6.8.0/bin/npm" "run" "update-schema"
npm ERR! node v6.8.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! leo-blog-starter@1.0.0 update-schema: `leo schema -u`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leo-blog-starter@1.0.0 update-schema script 'leo schema -u'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leo-blog-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     leo schema -u
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leo-blog-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leo-blog-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bdougie/Desktop/leo-blog-starter/npm-debug.log
```

**Comment by ChristopherBiscardi** [comment]
ah, you've hit a bug I fixed in a later version. This starter needs to be updated. Basically, the config for the markdown plugin accepts an optional configured markdown-it instance as an argument... except opts isn't defined in this version of the plugin if you don't have an appropriate config file so it errors out.

If you run these commands you'll get a working site that uses Apollo client (turns out Relay has some limitations in replacing the networking layer, etc). [github repo](https://github.com/ChristopherBiscardi/christopherbiscardi.github.com)

```
git clone git@github.com:ChristopherBiscardi/christopherbiscardi.github.com.git
cd christopherbiscardi.github.com
npm i
npm run update-schema
npm start
cd dist && python -m SimpleHTTPServer 8000
```

`update-schema` just writes out the graphql schema derived from the plugins into `dist` (in this case, blogpost and markdown).
`start` will do a one-pass build of the site.

---

I'm almost done with the upgrade to webpack 2.0 right now and will push a new version of this starter after that.

**Comment by bdougie** [comment]
Cool, thanks for the quick reply. Going to toy around with this tonight.

**Comment by ChristopherBiscardi** [comment]
starter was updated for 0.7.x line
